package green.dao.htj;

import android.database.sqlite.SQLiteDatabase;

import java.util.Map;

import de.greenrobot.dao.AbstractDao;
import de.greenrobot.dao.AbstractDaoSession;
import de.greenrobot.dao.identityscope.IdentityScopeType;
import de.greenrobot.dao.internal.DaoConfig;

import green.dao.htj.DeliveryOrder;
import green.dao.htj.StoreInfo;

import green.dao.htj.DeliveryOrderDao;
import green.dao.htj.StoreInfoDao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * {@inheritDoc}
 * 
 * @see de.greenrobot.dao.AbstractDaoSession
 */
public class DaoSession extends AbstractDaoSession {

    private final DaoConfig deliveryOrderDaoConfig;
    private final DaoConfig storeInfoDaoConfig;

    private final DeliveryOrderDao deliveryOrderDao;
    private final StoreInfoDao storeInfoDao;

    public DaoSession(SQLiteDatabase db, IdentityScopeType type, Map<Class<? extends AbstractDao<?, ?>>, DaoConfig>
            daoConfigMap) {
        super(db);

        deliveryOrderDaoConfig = daoConfigMap.get(DeliveryOrderDao.class).clone();
        deliveryOrderDaoConfig.initIdentityScope(type);

        storeInfoDaoConfig = daoConfigMap.get(StoreInfoDao.class).clone();
        storeInfoDaoConfig.initIdentityScope(type);

        deliveryOrderDao = new DeliveryOrderDao(deliveryOrderDaoConfig, this);
        storeInfoDao = new StoreInfoDao(storeInfoDaoConfig, this);

        registerDao(DeliveryOrder.class, deliveryOrderDao);
        registerDao(StoreInfo.class, storeInfoDao);
    }
    
    public void clear() {
        deliveryOrderDaoConfig.getIdentityScope().clear();
        storeInfoDaoConfig.getIdentityScope().clear();
    }

    public DeliveryOrderDao getDeliveryOrderDao() {
        return deliveryOrderDao;
    }

    public StoreInfoDao getStoreInfoDao() {
        return storeInfoDao;
    }

}
