package green.dao.htj;

import green.dao.htj.DaoSession;
import de.greenrobot.dao.DaoException;

// THIS CODE IS GENERATED BY greenDAO, EDIT ONLY INSIDE THE "KEEP"-SECTIONS

// KEEP INCLUDES - put your custom includes here
// KEEP INCLUDES END
/**
 * Entity mapped to table DELIVERY_ORDER.
 */
public class DeliveryOrder implements java.io.Serializable {

    private String order_id;
    private String customer_name;
    private String customer_mobile;
    private int customer_sex;
    /** Not-null value. */
    private String customer_address;
    private double customer_lng;
    private double customer_lat;
    private Integer status;
    private Integer reminderNumber;
    /** Not-null value. */
    private String deliverPhone;
    private Long lastReminderTime;
    private Long addTime;
    private String queryBatch;

    /** Used to resolve relations */
    private transient DaoSession daoSession;

    /** Used for active entity operations. */
    private transient DeliveryOrderDao myDao;


    // KEEP FIELDS - put your custom fields here
    // KEEP FIELDS END

    public DeliveryOrder() {
    }

    public DeliveryOrder(String order_id) {
        this.order_id = order_id;
    }

    public DeliveryOrder(String order_id, String customer_name, String customer_mobile, int customer_sex, String customer_address, double customer_lng, double customer_lat, Integer status, Integer reminderNumber, String deliverPhone, Long lastReminderTime, Long addTime, String queryBatch) {
        this.order_id = order_id;
        this.customer_name = customer_name;
        this.customer_mobile = customer_mobile;
        this.customer_sex = customer_sex;
        this.customer_address = customer_address;
        this.customer_lng = customer_lng;
        this.customer_lat = customer_lat;
        this.status = status;
        this.reminderNumber = reminderNumber;
        this.deliverPhone = deliverPhone;
        this.lastReminderTime = lastReminderTime;
        this.addTime = addTime;
        this.queryBatch = queryBatch;
    }

    /** called by internal mechanisms, do not call yourself. */
    public void __setDaoSession(DaoSession daoSession) {
        this.daoSession = daoSession;
        myDao = daoSession != null ? daoSession.getDeliveryOrderDao() : null;
    }

    public String getOrder_id() {
        return order_id;
    }

    public void setOrder_id(String order_id) {
        this.order_id = order_id;
    }

    public String getCustomer_name() {
        return customer_name;
    }

    public void setCustomer_name(String customer_name) {
        this.customer_name = customer_name;
    }

    public String getCustomer_mobile() {
        return customer_mobile;
    }

    public void setCustomer_mobile(String customer_mobile) {
        this.customer_mobile = customer_mobile;
    }

    public int getCustomer_sex() {
        return customer_sex;
    }

    public void setCustomer_sex(int customer_sex) {
        this.customer_sex = customer_sex;
    }

    /** Not-null value. */
    public String getCustomer_address() {
        return customer_address;
    }

    /** Not-null value; ensure this value is available before it is saved to the database. */
    public void setCustomer_address(String customer_address) {
        this.customer_address = customer_address;
    }

    public double getCustomer_lng() {
        return customer_lng;
    }

    public void setCustomer_lng(double customer_lng) {
        this.customer_lng = customer_lng;
    }

    public double getCustomer_lat() {
        return customer_lat;
    }

    public void setCustomer_lat(double customer_lat) {
        this.customer_lat = customer_lat;
    }

    public Integer getStatus() {
        return status;
    }

    public void setStatus(Integer status) {
        this.status = status;
    }

    public Integer getReminderNumber() {
        return reminderNumber;
    }

    public void setReminderNumber(Integer reminderNumber) {
        this.reminderNumber = reminderNumber;
    }

    /** Not-null value. */
    public String getDeliverPhone() {
        return deliverPhone;
    }

    /** Not-null value; ensure this value is available before it is saved to the database. */
    public void setDeliverPhone(String deliverPhone) {
        this.deliverPhone = deliverPhone;
    }

    public Long getLastReminderTime() {
        return lastReminderTime;
    }

    public void setLastReminderTime(Long lastReminderTime) {
        this.lastReminderTime = lastReminderTime;
    }

    public Long getAddTime() {
        return addTime;
    }

    public void setAddTime(Long addTime) {
        this.addTime = addTime;
    }

    public String getQueryBatch() {
        return queryBatch;
    }

    public void setQueryBatch(String queryBatch) {
        this.queryBatch = queryBatch;
    }

    /** Convenient call for {@link AbstractDao#delete(Object)}. Entity must attached to an entity context. */
    public void delete() {
        if (myDao == null) {
            throw new DaoException("Entity is detached from DAO context");
        }    
        myDao.delete(this);
    }

    /** Convenient call for {@link AbstractDao#update(Object)}. Entity must attached to an entity context. */
    public void update() {
        if (myDao == null) {
            throw new DaoException("Entity is detached from DAO context");
        }    
        myDao.update(this);
    }

    /** Convenient call for {@link AbstractDao#refresh(Object)}. Entity must attached to an entity context. */
    public void refresh() {
        if (myDao == null) {
            throw new DaoException("Entity is detached from DAO context");
        }    
        myDao.refresh(this);
    }

    // KEEP METHODS - put your custom methods here
    // KEEP METHODS END

}
